version: "3"

services:
    go4success:
        build:
            context: apps/frontend
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        environment:
            - NODE_ENV=development
            - FRONTEND_PORT=${FRONTEND_PORT:-8081} 
        tty: true
        ports:
            - "${FRONTEND_PORT:-8081}:8081"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ${FRONT_PATH}:/opt/go4success/app:delegated
            - ${FRONT_PATH}/package.json:/opt/go4success/package.json
            - ${FRONT_PATH}package-lock.json:/opt/go4success/package-lock.json

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    backend:
        build:
            context: apps/backend
            dockerfile: Dockerfile
        environment:
            - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
            - SECRET_KEY=${SECRET_KEY}
            - DB_HOST=${POSTGRES_DB:-localhost}
            - POSTGRES_DB=${DB_PORT:-5432}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - BACKEND_PORT=${BACKEND_PORT:-8000} 
        command: python manage.py runserver 0.0.0.0:${BACKEND_PORT:-8000}
        volumes:
            - ${BACK_PATH}:/app
        ports:
            - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
        depends_on:
            - db
