version: "3"

services:
    go4success:
        build:
            context: ./apps/frontend
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        environment:
            - NODE_ENV=development
        tty: true
        ports:
            - "8081:8081"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ./apps/frontend/go4success:/opt/go4success/app:delegated
            - ./apps/frontend/go4success/package.json:/opt/go4success/package.json
            - ./apps/frontend/go4success/package-lock.json:/opt/go4success/package-lock.json

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432

    backend:
        build:
            context: ./apps/backend
            dockerfile: Dockerfile
        env_file:
            - .env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./apps/backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
