version: "3"

services:
    go4success:
        pull_policy: build
        build:
            context: apps/frontend
            dockerfile: Dockerfile
            args:
                - BACKEND_API_URL=${BACKEND_API_URL}
        environment:
            - FRONTEND_PORT=${FRONTEND_PORT:-8081}
        tty: true
        ports:
            - "${FRONTEND_PORT:-8081}:3000"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ${FRONT_PATH}:/opt/go4success/app:delegated
            - ${FRONT_PATH}/package.json:/opt/go4success/package.json

            #- ${FRONT_PATH}/package-lock.json:/opt/go4success/package-lock.json

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${DB_PORT:-5432}:5432

    backend:
        pull_policy: build
        build:
            context: apps/backend
            dockerfile: Dockerfile
        environment:
            - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
            - SECRET_KEY=${SECRET_KEY}
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-5432}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - BACKEND_PORT=${BACKEND_PORT:-8000}
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${BACKEND_PORT:-8000}"
        ports:
            - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
        depends_on:
            - db
