version: "3"

services:
    go4success:
        build:
            context: ./apps/frontend
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        environment:
            - NODE_ENV=development
        tty: true
        ports:
            - "8081:8081"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ./apps/frontend/go4success:/opt/go4success/app:delegated
            - ./apps/frontend/go4success/package.json:/opt/go4success/package.json
            - ./apps/frontend/go4success/package-lock.json:/opt/go4success/package-lock.json

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    backend:
        build:
            context: ./apps/backend
            dockerfile: Dockerfile
        environment:
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - SECRET_KEY=${SECRET_KEY}
            - DB_HOST=${POSTGRES_DB:-localhost}
            - POSTGRES_DB=${DB_PORT:-5432}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - BACKEND_PORT=${BACKEND_PORT:-8000} 
        command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
        volumes:
            - ./apps/backend:/app
        ports:
            - "${BACKEND_PORT:-8000}:${BACKEND_PORT}"
        depends_on:
            - db
