# Generated by Django 5.0.4 on 2024-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user_id',
            new_name='user',
        ),
    ]
