# Generated by Django 5.0.3 on 2024-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feedbackadditionalquestions',
            name='question',
            field=models.TextField(),
        ),
    ]
