# Generated by Django 5.0.4 on 2024-05-05 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='noma',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Ce noma est déjà utilisé.'}, max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ClosedQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.TextField()),
                ('checked', models.BooleanField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.question')),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExpoToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'token')},
            },
        ),
    ]
