# Generated by Django 5.0.4 on 2024-05-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_course_user_alter_user_noma_closedquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.question'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.question'),
        ),
    ]
